FROM python:3.12-slim

WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends gcc libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY api/ .
COPY etl/ ./etl
COPY db/migrations ./db_migrations

ENV PYTHONUNBUFFERED=1

EXPOSE 8000

CMD ["sh", "./scripts/start_render.sh"]
